OnTheRoad/OnTheRoad.MVC/Areas/User/Models/ChatViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace OnTheRoad.MVC.Areas.User.Models
{
    public class ChatViewModel
    {
        public IEnumerable<MessageViewModel> Messages { get; set; }

        public string TargetUser { get; set; }
    }
}

OnTheRoad/OnTheRoad.MVC/Areas/User/Models/ConversationViewModel.cs
using OnTheRoad.Domain.Models;
using OnTheRoad.Infrastructure.Contracts;
using System.Collections.Generic;

namespace OnTheRoad.MVC.Areas.User.Models
{
    public class ConversationViewModel : IMapFrom<IConversation>
    {
        public string FirstUserUsername { get; set; }

        public byte[] FirstUserImage { get; set; }

        public string SecondUserUsername { get; set; }

        public byte[] SecondUserImage { get; set; }

        public string LastMessage { get; set; }

        //public IEnumerable<MessageViewModel> Messages { get; set; }
    }
}

OnTheRoad/OnTheRoad.MVC/Areas/User/Models/MessageViewModel.cs
using OnTheRoad.Domain.Models;
using OnTheRoad.Infrastructure.Contracts;
using System;

namespace OnTheRoad.MVC.Areas.User.Models
{
    public class MessageViewModel : IMapFrom<IMessage>
    {
        public string Text { get; set; }

        public DateTime CreateDate { get; set; }

        public string AuthorUsername { get; set; }

        public byte[] AuthorImage { get; set; }
    }
}

OnTheRoad/OnTheRoad.MVC/Areas/User/Models/MessagesViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace OnTheRoad.MVC.Areas.User.Models
{
    public class MessagesViewModel
    {
        public bool IsOwner { get; set; }
    }
}

OnTheRoad/OnTheRoad.MVC/Areas/User/Controllers/MessagesController.cs
using OnTheRoad.Logic.Contracts;
using OnTheRoad.MVC.Areas.User.Models;
using OnTheRoad.MVC.Common;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnTheRoad.MVC.Areas.User.Controllers
{
    public class MessagesController : Controller
    {
        private readonly IConversationService conversationService;

        public MessagesController(IConversationService conversationService)
        {
            if (conversationService == null)
            {
                throw new ArgumentNullException("conversationService can not be null!");
            }

            this.conversationService = conversationService;
        }

        [HttpGet]
        [Authorize]
        public ActionResult Index(string username)
        {
            var loggedUsername = ControllerUtilProvider.ControllerUtil.LoggedUserName;
            var isOwner = username == loggedUsername;

            var model = new MessagesViewModel();
            model.IsOwner = isOwner;

            return View(model);
        }

        [HttpGet]
        [Authorize]
        public ActionResult Conversations()
        {
            var loggedUsername = ControllerUtilProvider.ControllerUtil.LoggedUserName;
            var conversations = this.conversationService.GetConversationsForUser(loggedUsername);

            var model = new List<ConversationViewModel>();
            foreach (var conversation in conversations)
            {
                var mapped = MapperProvider.Mapper.Map<ConversationViewModel>(conversation);
                var lastMessage = conversation.Messages.OrderByDescending(x => x.CreateDate).Take(1).FirstOrDefault().Text;
                mapped.LastMessage = lastMessage;
                model.Add(mapped);
            }

            return this.View(model);
        }

        [HttpGet]
        [Authorize]
        public ActionResult Chat(string username)
        {
            var loggedUsername = ControllerUtilProvider.ControllerUtil.LoggedUserName;
            var conversationExist = this.conversationService.DoesConversationForUsersExist(loggedUsername, username);

            IEnumerable<MessageViewModel> mappedMessages;
            if (conversationExist)
            {
                var conversation = this.conversationService.GetConversationForUsers(loggedUsername, username);
                var conversationMessages = conversation.Messages;

                mappedMessages = MapperProvider.Mapper.Map<IEnumerable<MessageViewModel>>(conversationMessages);
            }
            else
            {
                mappedMessages = new List<MessageViewModel>();
            }

            var model = new ChatViewModel();
            model.Messages = mappedMessages;

            model.TargetUser = username;

            return PartialView(model);
        }
    }
}

OnTheRoad/OnTheRoad.MVC/Areas/User/Views/Messages/Chat.cshtml
@model ChatViewModel

@{
    Layout = null;
}

<div class="row" id="chat">
    <div class="col-sm-8 col-md-8 col-lg-8 messages"
         id="messages-container"
         author="@User.Identity.Name"
         target-user="@this.Model.TargetUser">
        @foreach (var message in this.Model.Messages)
        {
            if (User.Identity.Name == message.AuthorUsername)
            {
                <div class="message author">@message.Text</div>
            }
            else
            {
                <div class="message">@message.Text</div>
            }
        }
    </div>

    <div class="col-sm-12 col-md-12 col-lg-12 row">
        <div class="col-sm-12 col-md-6 col-lg-6">
            <textarea class="form-control" id="message"></textarea>
        </div>
        <div class="col-sm-12 col-md-2 col-lg-2">
            <button class="btn btn-lg btn-success" id="send-message">@Resources.User.Labels.Send</button>
        </div>
    </div>
</div>

OnTheRoad/OnTheRoad.MVC/Areas/User/Views/Messages/Conversations.cshtml
@model IEnumerable<ConversationViewModel>

@{
    Layout = null;
    var loggedUsername = this.User.Identity.Name;
}

@foreach (var conversation in this.Model)
{
    string username;
    byte[] image;
    if (loggedUsername == conversation.FirstUserUsername)
    {
        username = conversation.SecondUserUsername;
        image = conversation.SecondUserImage;
    }
    else
    {
        username = conversation.FirstUserUsername;
        image = conversation.FirstUserImage;
    }

    <div class="row conversation" username="@username">
        <div class="col-sm-12 col-md-2 col-lg-2">
            <img src="data:image/jpeg;base64,@Convert.ToBase64String(image)" class="favUserImage img-circle" />
        </div>
        <div class="col-sm-12 col-md-10 col-lg-10">
            <div class="message-author margin-left-1em">@username</div>
            <div class="message-text margin-left-1em">@conversation.LastMessage</div>
        </div>
    </div>
}

@if (this.Model.Count() == 0)
{
    <div class="notification-message">@Resources.User.Messages.NoConversationsYet</div>
}

OnTheRoad/OnTheRoad.MVC/Areas/User/Views/Messages/Index.cshtml
@model MessagesViewModel

@{ 
    var username = (string)this.ViewContext.RouteData.Values["username"];
}

<div class="row back-container box-shadow">
    @if (this.Model.IsOwner)
    {
        <div class="col-sm-12 col-md-4 col-lg-4">
            @Html.Action("Conversations", "Messages")
        </div>
        <div class="col-sm-12 col-md-8 col-lg-8" id="chat-container">
        </div>
    }
    else
    {
        <div class="col-sm-12 col-md-8 col-lg-8">
            @Html.Action("Chat", "Messages", new { username = username })
        </div>
    }
</div>