OnTheRoad/OnTheRoad.MVC/Models/NavigationPartialViewModel.cs
using OnTheRoad.Domain.Models;
using System.Collections.Generic;

namespace OnTheRoad.MVC.Models
{
    public class NavigationPartialViewModel
    {
        public IEnumerable<ICategory> Categories { get; set; }
    }
}

OnTheRoad/OnTheRoad.MVC/Models/TripsWithPagingViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace OnTheRoad.MVC.Models
{
    public class TripsWithPagingViewModel
    {
        public string Heading { get; set; }

        public string PageHyperLink { get; set; }

        public IEnumerable<TripViewModel> Trips { get; set; }

        public int Page { get; set; }

        public int Take { get; set; }

        public int Total { get; set; }
    }
}

OnTheRoad/OnTheRoad.MVC/Controllers/CategoriesController.cs
using OnTheRoad.Domain.Models;
using OnTheRoad.Logic.Contracts;
using OnTheRoad.MVC.Common;
using OnTheRoad.MVC.Models;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace OnTheRoad.MVC.Controllers
{
    public class CategoriesController : Controller
    {
        private const int Take = 3;

        private readonly ICategoryGetService categoryService;
        private readonly ITripGetService tripGetService;

        public CategoriesController(ICategoryGetService categoryService, ITripGetService tripGetService)
        {
            if (categoryService == null)
            {
                throw new ArgumentNullException("categoryService cannot be null!");
            }

            if (tripGetService == null)
            {
                throw new ArgumentNullException("tripGetService cannot be null!");
            }

            this.categoryService = categoryService;
            this.tripGetService = tripGetService;
        }

        [HttpGet]
        public ActionResult Index()
        {
            var categories = this.categoryService.GetAllCategories();
            var mappedCategories = new List<CategoryViewModel>();
            foreach (var category in categories)
            {
                var mappedCategory = MapperProvider.Mapper.Map<CategoryViewModel>(category);
                mappedCategories.Add(mappedCategory);
            }

            return this.View(mappedCategories);
        }

        [HttpGet]
        public ActionResult Details(string categoryName, int page = 1)
        {
            page = page > 0 ? page : 1;
            var skip = (page - 1) * Take;
            var trips = this.GetTrips(categoryName, skip, Take);

            var mappedTrips = MapperProvider.Mapper.Map<IEnumerable<TripViewModel>>(trips);

            var total = this.GetTripsTotal(categoryName);

            var categoryModel = new TripsWithPagingViewModel();
            categoryModel.Trips = mappedTrips;
            categoryModel.Total = total;
            categoryModel.Heading = $"{Resources.Labels.Category} {categoryName}";
            categoryModel.PageHyperLink = $"/categories/details/{categoryName}/";
            categoryModel.Page = page;
            categoryModel.Take = Take;

            return this.View("_TripsWithPagingAndNavigation", categoryModel);
        }

        private IEnumerable<ITrip> GetTrips(string categoryName, int skip, int take)
        {
            IEnumerable<ITrip> trips;
            if (string.IsNullOrEmpty(categoryName) || string.IsNullOrWhiteSpace(categoryName))
            {
                trips = this.tripGetService.GetTrips(skip, take);
            }
            else
            {
                trips = this.tripGetService.GetTripsByCategoryName(categoryName, skip, take);
            }

            return trips;
        }

        private int GetTripsTotal(string categoryName)
        {
            int total;
            if (string.IsNullOrEmpty(categoryName) || string.IsNullOrWhiteSpace(categoryName))
            {
                total = this.tripGetService.GetTripsCount();
            }
            else
            {
                total = this.tripGetService.GetTripsCountByCategoryName(categoryName);
            }

            return total;
        }
    }
}

OnTheRoad/OnTheRoad.MVC/Controllers/CategoryOverviewPartialController.cs
using OnTheRoad.Logic.Contracts;
using OnTheRoad.MVC.Common;
using OnTheRoad.MVC.Models;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace OnTheRoad.MVC.Controllers
{
    public class CategoryOverviewPartialController : Controller
    {
        private const int TripsCount = 4;

        private readonly ITripGetService tripGetService;

        public CategoryOverviewPartialController(ITripGetService tripGetService)
        {
            if (tripGetService == null)
            {
                throw new ArgumentNullException("tripGetService cannot be null!");
            }

            this.tripGetService = tripGetService;
        }

        [HttpGet]
        public ActionResult Index(string categoryName)
        {
            var mappedTrips = new List<TripViewModel>();
            var trips = this.tripGetService.GetTripsByCategoryNameOrderedByDate(categoryName, TripsCount);
            foreach (var trip in trips)
            {
                var mappedTrip = MapperProvider.Mapper.Map<TripViewModel>(trip);
                mappedTrips.Add(mappedTrip);
            }

            var categoryOverviewModel = new CategoryOverviewViewModel();
            categoryOverviewModel.Name = categoryName;
            categoryOverviewModel.Trips = mappedTrips;

            return this.PartialView("_CategoryOverviewPartial", categoryOverviewModel);
        }
    }
}

OnTheRoad/OnTheRoad.MVC/Controllers/NavigationPartialController.cs
using OnTheRoad.Logic.Contracts;
using OnTheRoad.MVC.Models;
using System;
using System.Web.Mvc;

namespace OnTheRoad.MVC.Controllers
{
    public class NavigationPartialController : Controller
    {
        private readonly ICategoryService categoryService;

        public NavigationPartialController(ICategoryService categoryService)
        {
            if (categoryService == null)
            {
                throw new ArgumentNullException("categoryService can not be null!");
            }

            this.categoryService = categoryService;
        }

        [HttpGet]
        public ActionResult Index()
        {
            var categories = this.categoryService.GetAllCategories();
            var model = new NavigationPartialViewModel() { Categories = categories };

            return PartialView("_NavigationPartial", model);
        }
    }
}

OnTheRoad/OnTheRoad.MVC/Controllers/TripsController.cs
using OnTheRoad.Domain.Enumerations;
using OnTheRoad.Infrastructure.Enums;
using OnTheRoad.Infrastructure.Json;
using OnTheRoad.Logic.Contracts;
using OnTheRoad.MVC.Common;
using OnTheRoad.MVC.Extensions;
using OnTheRoad.MVC.Filters;
using OnTheRoad.MVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace OnTheRoad.MVC.Controllers
{
    public class TripsController : Controller
    {
        private const int Take = 3;

        private readonly ITripService tripService;
        private readonly ISubscriptionService subscriptionService;
        private readonly ICategoryService categoryService;
        private readonly IImageService imageService;
        private readonly ITripBuilder tripBuilder;

        public TripsController(
            ITripService tripService,
            ISubscriptionService subscriptionService,
            ICategoryService categoryService,
            IImageService imageService,
            ITripBuilder tripBuilder)
        {
            if (tripService == null)
            {
                throw new ArgumentNullException("tripService cannot be null!");
            }

            if (subscriptionService == null)
            {
                throw new ArgumentNullException("subscriptionAddService can not be null!");
            }

            if (categoryService == null)
            {
                throw new ArgumentNullException("categoryService can not be null!");
            }

            if (imageService == null)
            {
                throw new ArgumentNullException("imageService cannot be null!");
            }

            if (tripBuilder == null)
            {
                throw new ArgumentNullException("tripBuilder cannot be null!");
            }

            this.tripService = tripService;
            this.subscriptionService = subscriptionService;
            this.categoryService = categoryService;
            this.imageService = imageService;
            this.tripBuilder = tripBuilder;
        }

        [HttpGet]
        public ActionResult Search(string pattern, int page = 1)
        {
            var categoryModel = new TripsWithPagingViewModel();
            categoryModel.Heading = $"{Resources.Labels.SearchResultsFor}: {pattern}";
            categoryModel.PageHyperLink = $"/trips/search/{pattern}/";

            if (string.IsNullOrEmpty(pattern) || string.IsNullOrWhiteSpace(pattern))
            {
                categoryModel.Trips = new List<TripViewModel>();
                categoryModel.Page = 1;
            }
            else
            {
                page = page > 0 ? page : 1;
                var skip = (page - 1) * Take;
                var trips = this.tripService.GetTripsBySearchPattern(pattern, skip, Take);
                var mappedTrips = MapperProvider.Mapper.Map<IEnumerable<TripViewModel>>(trips);

                var total = this.tripService.GetTripsCountBySearchPattern(pattern);

                categoryModel.Page = page;
                categoryModel.Trips = mappedTrips;
                categoryModel.Total = total;
                categoryModel.Take = Take;
            }

            return this.View("_TripsWithPagingAndNavigation", categoryModel);
        }

        [HttpGet]
        public ActionResult Details(int id)
        {
            var trip = this.tripService.GetTripById(id);

            var model = MapperProvider.Mapper.Map<TripDetailsViewModel>(trip);

            var userName = ControllerUtilProvider.ControllerUtil.LoggedUserName;
            var isOrganiser = userName == trip.Organiser.Username;
            var isAvailable = ControllerUtilProvider.ControllerUtil.IsAuthenticated && !isOrganiser;
            model.CanSubscribe = isAvailable;

            var subscriptionStatus = this.subscriptionService.GetUserSubscriptionStatus(trip, userName);
            model.IsNone = subscriptionStatus == SubscriptionStatus.None;
            model.IsAttending = subscriptionStatus == SubscriptionStatus.Attending;
            model.IsInterested = subscriptionStatus == SubscriptionStatus.Interested;

            return this.View(model);
        }

        [Authorize]
        [HttpPost]
        [Ajax]
        public ActionResult Subscribe(int tripId, string statusValue)
        {
            Result result;
            try
            {
                var status = (SubscriptionStatus)Enum.Parse(typeof(SubscriptionStatus), statusValue);
                var userName = ControllerUtilProvider.ControllerUtil.LoggedUserName;
                this.subscriptionService.AddOrUpdateSubscription(userName, tripId, status);

                result = new Result(Resources.Messages.SubscriptionSuccess, ResponseStatus.Ok);
            }
            catch (Exception)
            {
                result = new Result(Resources.Messages.SubscriptionError, ResponseStatus.ServerError);
                ControllerUtilProvider.ControllerUtil.SetResponseStatusCode(ResponseStatus.ServerError);
            }

            return this.Json(result);
        }

        [Authorize]
        [HttpGet]
        public ActionResult AddTrip()
        {
            var categories = this.categoryService.GetAllCategories();
            var listItems = new List<SelectListItem>();
            foreach (var category in categories)
            {
                var listItem = new SelectListItem() { Text = category.Name, Value = category.Id.ToString() };
                listItems.Add(listItem);
            }

            var model = new AddTripViewModel();
            model.AllCategories = listItems;

            var image = this.imageService.LoadTripsImage();
            model.CoverImage = image;

            return this.View(model);
        }

        [Authorize]
        [HttpPost]
        public ActionResult AddTrip(AddTripViewModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            var name = model.Name;
            var description = model.Description;
            var location = model.Location;
            var startDate = model.StartDate;
            var endDate = model.EndDate;
            var coverImage = model.CoverImage;

            var trip = this.tripBuilder
                .SetName(name)
                .SetDescription(description)
                .SetLocation(location)
                .SetStartDate(startDate)
                .SetEndDate(endDate)
                .SetImage(coverImage)
                .Build();

            var loggedUsername = ControllerUtilProvider.ControllerUtil.LoggedUserName;

            var categoryIds = model.CategoryIds.Select(int.Parse);
            var tagNames = model.TagNames.Distinct().Select(x => x.Trim());

            this.tripService.AddTrip(trip, loggedUsername, categoryIds, tagNames);

            this.AddToastMessage(string.Empty, Resources.Messages.AddTripSuccess, ToastType.Success);
            return this.RedirectToAction("Index", "Home");
        }
    }
}

OnTheRoad/OnTheRoad.MVC/Views/Shared/_CategoryOverviewPartial.cshtml
@model CategoryOverviewViewModel

<div class="trips-container text-center box-shadow">
    <div class="head box-shadow">
        <a href="/categories/details/@this.Model.Name">
            @this.Model.Name
        </a>
    </div>

    <div class="main row">
        @foreach (var trip in this.Model.Trips)
        {
            <div class="col-md-6 col-sm-6 col-xs-12">
                <div class="trip-item category-wrapper box-shadow overview-item">
                    <a href="/trips/details/@trip.Id">
                        <div class="meta-image text-center">
                            <img src="data:image/jpeg;base64,@Convert.ToBase64String(trip.CoverImage)" class="img-responsive resizable" />
                        </div>
                    </a>
                    <h4 class="trip-name">
                        <a href="/trips/details/@trip.Id">@trip.Name</a>
                    </h4>

                    <div class="info">
                        @Resources.Labels.Location:
                        <span>@trip.Location</span>
                    </div>
                    <div class="info">
                        @Resources.Labels.StartDate:
                        <span>@trip.StartDate.ToString("dd.MM.yyyy")</span>
                    </div>
                    <a href="/user/profile/@trip.OrganiserUsername" >
                        <div class="info">
                            @Resources.Labels.Organizer:
                            <span class="hyperlink">@trip.OrganiserFirstName @trip.OrganiserLastName</span>
                        </div>
                    </a>

                    <div class="oveflow-ellipsis-row-3">
                        @trip.Description
                    </div>
                </div>
            </div>
        }
    </div>
</div>

OnTheRoad/OnTheRoad.MVC/Views/Shared/_ImageUploaderPartial.cshtml
<form id="file-upload" action="/image/upload" method="post" class="margin-top-1em">
    <input type="file" name="file" class="btn-upload" width="95" id="image-upload" />
    <label for="image-upload" class="label-upload btn btn-xs btn-default">@Resources.Labels.ChooseImage</label>

    <input type="button" id="image-submit" value="@Resources.Labels.UploadImage" class="btn btn-xs btn-success" />
</form>

OnTheRoad/OnTheRoad.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - On The Road</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    @Styles.Render("~/Content/Styles/css")
    @Styles.Render("~/Content/toastr")
    @Styles.Render("~/content/jquery-ui")
    @RenderSection("styles", required: false)


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jquery-unobtrusive")
    @RenderSection("kendoScripts", required: false)

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("On The Road", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink(Resources.Labels.Trips, "Index", "Categories", new { area = "" }, null)</li>
                    @if (Request.IsAuthenticated)
                    {
                        <li>@Html.ActionLink(Resources.Labels.AddTrip, "AddTrip", "Trips", new { area = "" }, null)</li>
                        if (User.IsInRole("Admin"))
                        {
                            <li>@Html.ActionLink(Resources.Labels.Admin, "Index", "Trips", new { Area = "Administration" }, new { })</li>
                        }
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>

    @RenderSection("heading", required: false)

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - On The Road</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/toastr")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jquery-form")
    @Scripts.Render("~/bundles/jquery-ui")
    @Scripts.Render("~/bundles/jquery-signalR")
    @Scripts.Render("~/signalr/hubs")
    @Scripts.Render("~/bundles/microsoft-ajax")
    @Scripts.Render("~/bundles/microsoft-validation")
    @Scripts.Render("~/Content/Scripts/js")
    @RenderSection("scripts", required: false)

    @Html.Partial("_Toastr")
</body>
</html>

OnTheRoad/OnTheRoad.MVC/Views/Shared/_LoaderPartial.cshtml
<div class="windows8 hidden" id="loader">
    <div class="wBall" id="wBall_1">
        <div class="wInnerBall"></div>
    </div>
    <div class="wBall" id="wBall_2">
        <div class="wInnerBall"></div>
    </div>
    <div class="wBall" id="wBall_3">
        <div class="wInnerBall"></div>
    </div>
    <div class="wBall" id="wBall_4">
        <div class="wInnerBall"></div>
    </div>
    <div class="wBall" id="wBall_5">
        <div class="wInnerBall"></div>
    </div>
</div>

OnTheRoad/OnTheRoad.MVC/Views/Shared/_NavigationPartial.cshtml
@model NavigationPartialViewModel

@{
    Layout = null;
}

<div class="nav-area">
    <div class="search-container box-shadow">
        <div class="nav-head text-center box-shadow">
            <span>@Resources.Labels.Search</span>
        </div>
        <div class="search-body text-center">
            <div>
                <input id="search-box" type="text" class="search-box" />
                <a id="search-btn" class="search-button text-center">
                    <i class="fa fa-search"></i>
                </a>
            </div>
        </div>
    </div>
    <div class="nav-categories-container box-shadow">
        <div class="nav-head text-center box-shadow">
            <span>@Resources.Labels.TripsCategories</span>
        </div>
        <div class="nav-categories-body box-shadow">
            <div>
                @foreach (var category in this.Model.Categories)
                {
                    <a href="/categories/details/@category.Name" class="nav-category-item">
                        @category.Name
                    </a>
                }
            </div>
        </div>
    </div>
</div>

OnTheRoad/OnTheRoad.MVC/Views/Shared/_TagsSelectPartial.cshtml
<div class="float-left">
    <div class="col-md-offset-2" id="selected-tags">
    </div>

    <div class="form-group">
        <label for="tags" class="col-md-2 control-label input-labels" >@Resources.Labels.Tags</label>
        <div class="col-md-10">
            <input type="text" class="form-control tags-select-textbox" id="tags" />
            <input type="button" id="tag-submit" class="btn btn-small btn-success" value="@Resources.Labels.Add" />
        </div>
    </div>
</div>

OnTheRoad/OnTheRoad.MVC/Views/Shared/_Toastr.cshtml
@using OnTheRoad.Infrastructure.Wrappers
@using OnTheRoad.Infrastructure.Common
@if (TempData.ContainsKey(GlobalConstants.Toastr))
{
    Toastr toastr = TempData[GlobalConstants.Toastr] as Toastr;
    @ToastrBuilder.ShowToastMessages(toastr);
}

OnTheRoad/OnTheRoad.MVC/Views/Shared/_TripItemPartial.cshtml
@model TripViewModel

@{
    Layout = null;
}

<div class="trip-item row trips-wrapper box-shadow">
    <div class="col col-md-6 col-sm-6 col-xs-12">
        <a href="/trips/details/@this.Model.Id">
            <div class="meta-image text-center">
                <img src="data:image/jpeg;base64,@Convert.ToBase64String(this.Model.CoverImage)" class="img-responsive resizable" />
            </div>
        </a>
    </div>
    <div class="col-md-6 col-sm-6 col-xs-12">
        <h4>
            <a href="/trips/details/@this.Model.Id">
                @this.Model.Name
            </a>
        </h4>

        <div class="info">
            @Resources.Labels.Location:
            <span>@this.Model.Location</span>
        </div>
        <div class="info">
            @Resources.Labels.StartDate:
            <span>@this.Model.StartDate.ToString("dd.MM.yyyy")</span>
        </div>
        <a href="/user/profile/@this.Model.OrganiserUsername">
            <div class="info">
                @Resources.Labels.Organizer:
                <span class="hyperlink">@this.Model.OrganiserFirstName @this.Model.OrganiserLastName</span>
            </div>
        </a>
    </div>
</div>

OnTheRoad/OnTheRoad.MVC/Views/Shared/_TripsWithPaging.cshtml
@model TripsWithPagingViewModel

@{
    Layout = null;
}

<div class="col-lg-8 col-md-8 col-sm-12 col-xs-12" id="trips">
    <div class="trips-container text-center box-shadow">
        <div class="head box-shadow">
            <span>@this.Model.Heading</span>
        </div>

        <div class="main">
            @foreach (var trip in this.Model.Trips)
            {
                Html.RenderPartial("_TripItemPartial", trip);
            }

            <div class="pager text-center">
                @if (this.Model.Page == 1)
                {
                    <a id="prev-page" class="arrow arrow-left disabled"></a>
                }
                else
                {
                    <a id="prev-page" class="arrow arrow-left" href="@this.Model.PageHyperLink@(this.Model.Page - 1)"></a>
                }

                @if ((this.Model.Page * this.Model.Take) >= this.Model.Total)
                {
                    <a id="next-page" class="arrow arrow-right disabled"></a>
                }
                else
                {
                    <a id="next-page" class="arrow arrow-right" href="@this.Model.PageHyperLink@(this.Model.Page + 1)"></a>
                }
            </div>
        </div>
    </div>
</div>

OnTheRoad/OnTheRoad.MVC/Views/Shared/_TripsWithPagingAndNavigation.cshtml
@model TripsWithPagingViewModel

<div class="row">
    <div class="content-container">
        @Html.Partial("_TripsWithPaging", this.Model)
    </div>
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
        @Html.Action("Index", "NavigationPartial")
    </div>
</div>